package cn.com.shiro.book.entity;

import java.io.Serializable;
import java.util.List;

public class ShrRole implements Serializable {
	private List<ShrRolePermission> rlPermissions;
	private List<ShrUser> rlUsers;
	
    public List<ShrRolePermission> getRlPermissions() {
		return rlPermissions;
	}

	public void setRlPermissions(List<ShrRolePermission> rlPermissions) {
		this.rlPermissions = rlPermissions;
	}

	public List<ShrUser> getRlUsers() {
		return rlUsers;
	}

	public void setRlUsers(List<ShrUser> rlUsers) {
		this.rlUsers = rlUsers;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shr_role.rl_id
     *
     * @mbggenerated
     */
    private Integer rlId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shr_role.rl_name
     *
     * @mbggenerated
     */
    private String rlName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shr_role.rl_remark
     *
     * @mbggenerated
     */
    private String rlRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shr_role
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shr_role.rl_id
     *
     * @return the value of shr_role.rl_id
     *
     * @mbggenerated
     */
    public Integer getRlId() {
        return rlId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shr_role.rl_id
     *
     * @param rlId the value for shr_role.rl_id
     *
     * @mbggenerated
     */
    public void setRlId(Integer rlId) {
        this.rlId = rlId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shr_role.rl_name
     *
     * @return the value of shr_role.rl_name
     *
     * @mbggenerated
     */
    public String getRlName() {
        return rlName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shr_role.rl_name
     *
     * @param rlName the value for shr_role.rl_name
     *
     * @mbggenerated
     */
    public void setRlName(String rlName) {
        this.rlName = rlName == null ? null : rlName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shr_role.rl_remark
     *
     * @return the value of shr_role.rl_remark
     *
     * @mbggenerated
     */
    public String getRlRemark() {
        return rlRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shr_role.rl_remark
     *
     * @param rlRemark the value for shr_role.rl_remark
     *
     * @mbggenerated
     */
    public void setRlRemark(String rlRemark) {
        this.rlRemark = rlRemark == null ? null : rlRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shr_role
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ShrRole other = (ShrRole) that;
        return (this.getRlId() == null ? other.getRlId() == null : this.getRlId().equals(other.getRlId()))
            && (this.getRlName() == null ? other.getRlName() == null : this.getRlName().equals(other.getRlName()))
            && (this.getRlRemark() == null ? other.getRlRemark() == null : this.getRlRemark().equals(other.getRlRemark()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shr_role
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getRlId() == null) ? 0 : getRlId().hashCode());
        result = prime * result + ((getRlName() == null) ? 0 : getRlName().hashCode());
        result = prime * result + ((getRlRemark() == null) ? 0 : getRlRemark().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shr_role
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", rlId=").append(rlId);
        sb.append(", rlName=").append(rlName);
        sb.append(", rlRemark=").append(rlRemark);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}