package cn.com.shiro.book.entity;

import java.io.Serializable;

public class ShrResourceItem implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shr_resource_item.itm_id
     *
     * @mbggenerated
     */
    private Integer itmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shr_resource_item.itm_type
     *
     * @mbggenerated
     */
    private Integer itmType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shr_resource_item.itm_url
     *
     * @mbggenerated
     */
    private String itmUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shr_resource_item.itm_remark
     *
     * @mbggenerated
     */
    private String itmRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shr_resource_item.itm_rsc_id
     *
     * @mbggenerated
     */
    private ShrResource itmResource;
    private Integer itmRscId;

    public Integer getItmRscId() {
    	if(this.itmResource != null){
    		return this.itmResource.getRscId();
    	}
		return itmRscId;
	}

	public void setItmRscId(Integer itmRscId) {
		//this.itmRscId = itmRscId;
		if(this.itmResource == null){
			this.itmResource = new ShrResource();
		}
		this.itmResource.setRscId(itmRscId);
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shr_resource_item
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shr_resource_item.itm_id
     *
     * @return the value of shr_resource_item.itm_id
     *
     * @mbggenerated
     */
    public Integer getItmId() {
        return itmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shr_resource_item.itm_id
     *
     * @param itmId the value for shr_resource_item.itm_id
     *
     * @mbggenerated
     */
    public void setItmId(Integer itmId) {
        this.itmId = itmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shr_resource_item.itm_type
     *
     * @return the value of shr_resource_item.itm_type
     *
     * @mbggenerated
     */
    public Integer getItmType() {
        return itmType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shr_resource_item.itm_type
     *
     * @param itmType the value for shr_resource_item.itm_type
     *
     * @mbggenerated
     */
    public void setItmType(Integer itmType) {
        this.itmType = itmType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shr_resource_item.itm_url
     *
     * @return the value of shr_resource_item.itm_url
     *
     * @mbggenerated
     */
    public String getItmUrl() {
        return itmUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shr_resource_item.itm_url
     *
     * @param itmUrl the value for shr_resource_item.itm_url
     *
     * @mbggenerated
     */
    public void setItmUrl(String itmUrl) {
        this.itmUrl = itmUrl == null ? null : itmUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shr_resource_item.itm_remark
     *
     * @return the value of shr_resource_item.itm_remark
     *
     * @mbggenerated
     */
    public String getItmRemark() {
        return itmRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shr_resource_item.itm_remark
     *
     * @param itmRemark the value for shr_resource_item.itm_remark
     *
     * @mbggenerated
     */
    public void setItmRemark(String itmRemark) {
        this.itmRemark = itmRemark == null ? null : itmRemark.trim();
    }

    

    public ShrResource getItmResource() {
		return itmResource;
	}

	public void setItmResource(ShrResource itmResource) {
		this.itmResource = itmResource;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shr_resource_item
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ShrResourceItem other = (ShrResourceItem) that;
        return (this.getItmId() == null ? other.getItmId() == null : this.getItmId().equals(other.getItmId()))
            && (this.getItmType() == null ? other.getItmType() == null : this.getItmType().equals(other.getItmType()))
            && (this.getItmUrl() == null ? other.getItmUrl() == null : this.getItmUrl().equals(other.getItmUrl()))
            && (this.getItmRemark() == null ? other.getItmRemark() == null : this.getItmRemark().equals(other.getItmRemark()))
            && (this.getItmResource() == null ? other.getItmResource() == null : this.getItmResource().equals(other.getItmResource()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shr_resource_item
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getItmId() == null) ? 0 : getItmId().hashCode());
        result = prime * result + ((getItmType() == null) ? 0 : getItmType().hashCode());
        result = prime * result + ((getItmUrl() == null) ? 0 : getItmUrl().hashCode());
        result = prime * result + ((getItmRemark() == null) ? 0 : getItmRemark().hashCode());
        result = prime * result + ((getItmResource() == null) ? 0 : getItmResource().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shr_resource_item
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", itmId=").append(itmId);
        sb.append(", itmType=").append(itmType);
        sb.append(", itmUrl=").append(itmUrl);
        sb.append(", itmRemark=").append(itmRemark);
        if(this.getItmResource() != null)
        sb.append(", itmRscId=").append(this.getItmResource().getRscId());
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}