package cn.com.shiro.book.entity;

import java.io.Serializable;
import java.util.List;

public class ShrResource implements Serializable {
	private List<ShrUserPermission> rscUserPermissions;
	private List<ShrRolePermission> rscRolePermissions;
	private List<ShrResourceItem> rscItems;
	
	
    public List<ShrUserPermission> getRscUserPermissions() {
		return rscUserPermissions;
	}

	public void setRscUserPermissions(List<ShrUserPermission> rscUserPermissions) {
		this.rscUserPermissions = rscUserPermissions;
	}

	public List<ShrRolePermission> getRscRolePermissions() {
		return rscRolePermissions;
	}

	public void setRscRolePermissions(List<ShrRolePermission> rscRolePermissions) {
		this.rscRolePermissions = rscRolePermissions;
	}

	public List<ShrResourceItem> getRscItems() {
		return rscItems;
	}

	public void setRscItems(List<ShrResourceItem> rscItems) {
		this.rscItems = rscItems;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shr_resource.rsc_id
     *
     * @mbggenerated
     */
    private Integer rscId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shr_resource.rsc_name
     *
     * @mbggenerated
     */
    private String rscName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shr_resource.rsc_remark
     *
     * @mbggenerated
     */
    private String rscRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shr_resource
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shr_resource.rsc_id
     *
     * @return the value of shr_resource.rsc_id
     *
     * @mbggenerated
     */
    public Integer getRscId() {
        return rscId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shr_resource.rsc_id
     *
     * @param rscId the value for shr_resource.rsc_id
     *
     * @mbggenerated
     */
    public void setRscId(Integer rscId) {
        this.rscId = rscId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shr_resource.rsc_name
     *
     * @return the value of shr_resource.rsc_name
     *
     * @mbggenerated
     */
    public String getRscName() {
        return rscName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shr_resource.rsc_name
     *
     * @param rscName the value for shr_resource.rsc_name
     *
     * @mbggenerated
     */
    public void setRscName(String rscName) {
        this.rscName = rscName == null ? null : rscName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shr_resource.rsc_remark
     *
     * @return the value of shr_resource.rsc_remark
     *
     * @mbggenerated
     */
    public String getRscRemark() {
        return rscRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shr_resource.rsc_remark
     *
     * @param rscRemark the value for shr_resource.rsc_remark
     *
     * @mbggenerated
     */
    public void setRscRemark(String rscRemark) {
        this.rscRemark = rscRemark == null ? null : rscRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shr_resource
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ShrResource other = (ShrResource) that;
        return (this.getRscId() == null ? other.getRscId() == null : this.getRscId().equals(other.getRscId()))
            && (this.getRscName() == null ? other.getRscName() == null : this.getRscName().equals(other.getRscName()))
            && (this.getRscRemark() == null ? other.getRscRemark() == null : this.getRscRemark().equals(other.getRscRemark()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shr_resource
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getRscId() == null) ? 0 : getRscId().hashCode());
        result = prime * result + ((getRscName() == null) ? 0 : getRscName().hashCode());
        result = prime * result + ((getRscRemark() == null) ? 0 : getRscRemark().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shr_resource
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", rscId=").append(rscId);
        sb.append(", rscName=").append(rscName);
        sb.append(", rscRemark=").append(rscRemark);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}