package cn.com.shiro.book.entity;

import java.io.Serializable;
import java.util.List;

public class ShrUser implements Serializable {
	private List<ShrUserPermission> urPermissions;
	private List<ShrRole> urRoles;
	
    public List<ShrUserPermission> getUrPermissions() {
		return urPermissions;
	}

	public void setUrPermissions(List<ShrUserPermission> urPermissions) {
		this.urPermissions = urPermissions;
	}

	public List<ShrRole> getUrRoles() {
		return urRoles;
	}

	public void setUrRoles(List<ShrRole> urRoles) {
		this.urRoles = urRoles;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shr_user.ur_id
     *
     * @mbggenerated
     */
    private Integer urId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shr_user.ur_user_name
     *
     * @mbggenerated
     */
    private String urUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shr_user.ur_password
     *
     * @mbggenerated
     */
    private String urPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shr_user.ur_salt
     *
     * @mbggenerated
     */
    private String urSalt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shr_user
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shr_user.ur_id
     *
     * @return the value of shr_user.ur_id
     *
     * @mbggenerated
     */
    public Integer getUrId() {
        return urId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shr_user.ur_id
     *
     * @param urId the value for shr_user.ur_id
     *
     * @mbggenerated
     */
    public void setUrId(Integer urId) {
        this.urId = urId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shr_user.ur_user_name
     *
     * @return the value of shr_user.ur_user_name
     *
     * @mbggenerated
     */
    public String getUrUserName() {
        return urUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shr_user.ur_user_name
     *
     * @param urUserName the value for shr_user.ur_user_name
     *
     * @mbggenerated
     */
    public void setUrUserName(String urUserName) {
        this.urUserName = urUserName == null ? null : urUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shr_user.ur_password
     *
     * @return the value of shr_user.ur_password
     *
     * @mbggenerated
     */
    public String getUrPassword() {
        return urPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shr_user.ur_password
     *
     * @param urPassword the value for shr_user.ur_password
     *
     * @mbggenerated
     */
    public void setUrPassword(String urPassword) {
        this.urPassword = urPassword == null ? null : urPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shr_user.ur_salt
     *
     * @return the value of shr_user.ur_salt
     *
     * @mbggenerated
     */
    public String getUrSalt() {
        return urSalt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shr_user.ur_salt
     *
     * @param urSalt the value for shr_user.ur_salt
     *
     * @mbggenerated
     */
    public void setUrSalt(String urSalt) {
        this.urSalt = urSalt == null ? null : urSalt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shr_user
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ShrUser other = (ShrUser) that;
        return (this.getUrId() == null ? other.getUrId() == null : this.getUrId().equals(other.getUrId()))
            && (this.getUrUserName() == null ? other.getUrUserName() == null : this.getUrUserName().equals(other.getUrUserName()))
            && (this.getUrPassword() == null ? other.getUrPassword() == null : this.getUrPassword().equals(other.getUrPassword()))
            && (this.getUrSalt() == null ? other.getUrSalt() == null : this.getUrSalt().equals(other.getUrSalt()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shr_user
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUrId() == null) ? 0 : getUrId().hashCode());
        result = prime * result + ((getUrUserName() == null) ? 0 : getUrUserName().hashCode());
        result = prime * result + ((getUrPassword() == null) ? 0 : getUrPassword().hashCode());
        result = prime * result + ((getUrSalt() == null) ? 0 : getUrSalt().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shr_user
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", urId=").append(urId);
        sb.append(", urUserName=").append(urUserName);
        sb.append(", urPassword=").append(urPassword);
        sb.append(", urSalt=").append(urSalt);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}