package cn.com.shiro.book.entity;

import java.io.Serializable;

public class ShrUserPermission extends ShrPermission implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column shr_user_permission.prm_ur_id
	 * 
	 * @mbggenerated
	 */
	private ShrUser prmUser;
	private Integer prmUrId;

	private static final long serialVersionUID = 1L;

	public Integer getPrmUrId() {
		if(prmUser != null){
			return this.prmUser.getUrId();
		}
		return prmUrId;
	}

	public void setPrmUrId(Integer prmUrId) {
//		this.prmUrId = prmUrId;
		if(this.prmUser == null){
			this.prmUser = new ShrUser();
		}
		this.prmUser.setUrId(prmUrId);
	}

	public ShrUser getPrmUser() {
		return prmUser;
	}

	public void setPrmUser(ShrUser prmUser) {
		this.prmUser = prmUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table shr_user_permission
	 * 
	 * @mbggenerated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		ShrUserPermission other = (ShrUserPermission) that;
		return (this.getPrmId() == null ? other.getPrmId() == null : this
				.getPrmId().equals(other.getPrmId()))
				&& (this.getPrmUser() == null ? other.getPrmUser() == null
						: this.getPrmUser().equals(other.getPrmUser()))
				&& (this.getPrmResource() == null ? other.getPrmResource() == null
						: this.getPrmResource().equals(other.getPrmResource()))
				&& (this.getPrmOperationCode() == null ? other
						.getPrmOperationCode() == null : this
						.getPrmOperationCode().equals(
								other.getPrmOperationCode()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table shr_user_permission
	 * 
	 * @mbggenerated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((getPrmId() == null) ? 0 : getPrmId().hashCode());
		result = prime * result
				+ ((getPrmUser() == null) ? 0 : getPrmUser().hashCode());
		result = prime
				* result
				+ ((getPrmResource() == null) ? 0 : getPrmResource().hashCode());
		result = prime
				* result
				+ ((getPrmOperationCode() == null) ? 0 : getPrmOperationCode()
						.hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table shr_user_permission
	 * 
	 * @mbggenerated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());

		sb.append(", prmId=").append(this.getPrmId());
		if (this.getPrmUser() != null)
			sb.append(", prmUrId=").append(getPrmUser().getUrId());
		if (this.getPrmResource() != null)
			sb.append(", prmRscId=").append(getPrmResource().getRscId());
		sb.append(", prmOperationCode=").append(this.getPrmOperationCode());
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}